-- -------------------------------------------------------------
-- Supabase Schema for Acquire OPD Submissions
-- Run this in your Supabase SQL Editor (https://database.new)
-- -------------------------------------------------------------

-- =============================================================
-- 1. CREATE TABLES IF THEY DO NOT EXIST
-- =============================================================

CREATE TABLE IF NOT EXISTS public.assessment_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    hospital text NOT NULL,
    mobile text NOT NULL,
    email text NOT NULL,
    city text NOT NULL,
    message text,
    total_score integer DEFAULT 0,
    score integer DEFAULT 0,
    answers jsonb DEFAULT '{}'::jsonb,
    knockouts jsonb DEFAULT '{}'::jsonb,
    status text DEFAULT 'Pending Review',
    review_notes text,
    user_ip text,
    user_agent text
);

CREATE TABLE IF NOT EXISTS public.submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    hospital text NOT NULL,
    mobile text NOT NULL,
    email text NOT NULL,
    city text NOT NULL,
    message text,
    total_score integer DEFAULT 0,
    score integer DEFAULT 0,
    answers jsonb DEFAULT '{}'::jsonb,
    knockouts jsonb DEFAULT '{}'::jsonb,
    status text DEFAULT 'Pending Review',
    review_notes text,
    user_ip text,
    user_agent text
);

-- =============================================================
-- 2. ENSURE COLUMNS EXIST (IN CASE TABLES ALREADY EXISTED)
-- =============================================================

ALTER TABLE public.assessment_submissions ADD COLUMN IF NOT EXISTS status text DEFAULT 'Pending Review';
ALTER TABLE public.assessment_submissions ADD COLUMN IF NOT EXISTS review_notes text;

ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS status text DEFAULT 'Pending Review';
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS review_notes text;

-- =============================================================
-- 3. GRANT PERMISSIONS TO ANON & AUTHENTICATED & SERVICE_ROLE
-- =============================================================

GRANT ALL ON TABLE public.assessment_submissions TO anon;
GRANT ALL ON TABLE public.assessment_submissions TO authenticated;
GRANT ALL ON TABLE public.assessment_submissions TO service_role;

GRANT ALL ON TABLE public.submissions TO anon;
GRANT ALL ON TABLE public.submissions TO authenticated;
GRANT ALL ON TABLE public.submissions TO service_role;

-- =============================================================
-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- =============================================================

ALTER TABLE public.assessment_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- =============================================================
-- 5. APPLY FOOLPROOF PUBLIC INSERT & SELECT POLICIES
-- =============================================================

-- For assessment_submissions table
DROP POLICY IF EXISTS "Allow anonymous insertions" ON public.assessment_submissions;
DROP POLICY IF EXISTS "Allow public insertions" ON public.assessment_submissions;
CREATE POLICY "Allow public insertions" ON public.assessment_submissions
    FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select" ON public.assessment_submissions;
DROP POLICY IF EXISTS "Allow authenticated select" ON public.assessment_submissions;
CREATE POLICY "Allow public select" ON public.assessment_submissions
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow public update" ON public.assessment_submissions;
CREATE POLICY "Allow public update" ON public.assessment_submissions
    FOR UPDATE
    USING (true);

DROP POLICY IF EXISTS "Allow public delete" ON public.assessment_submissions;
CREATE POLICY "Allow public delete" ON public.assessment_submissions
    FOR DELETE
    USING (true);

-- For submissions table (fallback)
DROP POLICY IF EXISTS "Allow anonymous insertions" ON public.submissions;
DROP POLICY IF EXISTS "Allow public insertions" ON public.submissions;
CREATE POLICY "Allow public insertions" ON public.submissions
    FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select" ON public.submissions;
DROP POLICY IF EXISTS "Allow authenticated select" ON public.submissions;
CREATE POLICY "Allow public select" ON public.submissions
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow public update" ON public.submissions;
CREATE POLICY "Allow public update" ON public.submissions
    FOR UPDATE
    USING (true);

DROP POLICY IF EXISTS "Allow public delete" ON public.submissions;
CREATE POLICY "Allow public delete" ON public.submissions
    FOR DELETE
    USING (true);

-- =============================================================
-- 6. ADMIN CREDENTIALS TABLE (FOR DATABASE-STORED LOGINS)
-- =============================================================

CREATE TABLE IF NOT EXISTS public.admin_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text UNIQUE NOT NULL,
    password_hash text NOT NULL
);

GRANT ALL ON TABLE public.admin_credentials TO anon;
GRANT ALL ON TABLE public.admin_credentials TO authenticated;
GRANT ALL ON TABLE public.admin_credentials TO service_role;

ALTER TABLE public.admin_credentials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read-only queries for login validation" ON public.admin_credentials;
CREATE POLICY "Allow read-only queries for login validation" ON public.admin_credentials
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow public insertions for config" ON public.admin_credentials;
CREATE POLICY "Allow public insertions for config" ON public.admin_credentials
    FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public updates" ON public.admin_credentials;
CREATE POLICY "Allow public updates" ON public.admin_credentials
    FOR UPDATE
    USING (true);

-- Insert default admin user if not exists
INSERT INTO public.admin_credentials (email, password_hash)
VALUES ('admin@gmail.com', 'Welcome@123')
ON CONFLICT (email) DO NOTHING;

