-- -------------------------------------------------------------
-- Supabase Schema for Acquire OPD Submissions
-- Run this in your Supabase SQL Editor (https://database.new)
-- -------------------------------------------------------------

-- ==========================================
-- 1. CREATE TABLES IF THEY DO NOT EXIST
-- ==========================================

CREATE TABLE IF NOT EXISTS public.assessment_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    hospital text NOT NULL,
    mobile text NOT NULL,
    email text NOT NULL,
    city text NOT NULL,
    message text,
    total_score integer DEFAULT 0,
    score integer DEFAULT 0,
    answers jsonb DEFAULT '{}'::jsonb,
    knockouts jsonb DEFAULT '{}'::jsonb,
    user_ip text,
    user_agent text
);

CREATE TABLE IF NOT EXISTS public.submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    hospital text NOT NULL,
    mobile text NOT NULL,
    email text NOT NULL,
    city text NOT NULL,
    message text,
    total_score integer DEFAULT 0,
    score integer DEFAULT 0,
    answers jsonb DEFAULT '{}'::jsonb,
    knockouts jsonb DEFAULT '{}'::jsonb,
    user_ip text,
    user_agent text
);

-- ==========================================
-- 2. GRANT PERMISSIONS TO ANON & AUTHENTICATED
-- ==========================================

GRANT ALL ON TABLE public.assessment_submissions TO anon;
GRANT ALL ON TABLE public.assessment_submissions TO authenticated;
GRANT ALL ON TABLE public.assessment_submissions TO service_role;

GRANT ALL ON TABLE public.submissions TO anon;
GRANT ALL ON TABLE public.submissions TO authenticated;
GRANT ALL ON TABLE public.submissions TO service_role;

-- ==========================================
-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE public.assessment_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. APPLY FOOLPROOF PUBLIC INSERT POLICIES
-- ==========================================

-- For assessment_submissions table
DROP POLICY IF EXISTS "Allow anonymous insertions" ON public.assessment_submissions;
DROP POLICY IF EXISTS "Allow public insertions" ON public.assessment_submissions;
CREATE POLICY "Allow public insertions" ON public.assessment_submissions
    FOR INSERT
    WITH CHECK (true);

-- For submissions table (fallback)
DROP POLICY IF EXISTS "Allow anonymous insertions" ON public.submissions;
DROP POLICY IF EXISTS "Allow public insertions" ON public.submissions;
CREATE POLICY "Allow public insertions" ON public.submissions
    FOR INSERT
    WITH CHECK (true);

-- ==========================================
-- 5. APPLY SELECT POLICIES (FOR ADMINS / AUDITING)
-- ==========================================

-- Allow everyone to query entries if needed (or restrict to 'authenticated' as desired)
DROP POLICY IF EXISTS "Allow public select" ON public.assessment_submissions;
DROP POLICY IF EXISTS "Allow authenticated select" ON public.assessment_submissions;
CREATE POLICY "Allow public select" ON public.assessment_submissions
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow public select" ON public.submissions;
DROP POLICY IF EXISTS "Allow authenticated select" ON public.submissions;
CREATE POLICY "Allow public select" ON public.submissions
    FOR SELECT
    USING (true);
